# Generated by Django 4.2.3 on 2023-07-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_alter_features_options_alter_showroom_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="engine_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="engine",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="features",
            name="model",
            field=models.ManyToManyField(related_name="features", to="showroom.model"),
        ),
        migrations.AlterField(
            model_name="showroom",
            name="brands",
            field=models.ManyToManyField(related_name="showroom", to="showroom.brand"),
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chasis_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car",
                        to="showroom.model",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="engine",
            name="car",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engine",
                to="showroom.car",
            ),
        ),
    ]
