# Generated by Django 4.2.3 on 2023-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_engine_engine_number_alter_engine_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engine",
            name="car",
        ),
        migrations.AlterField(
            model_name="engine",
            name="engine_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
