# Generated by Django 4.2.3 on 2023-07-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0004_remove_engine_car_alter_engine_engine_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="car",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engine",
                to="showroom.car",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="chasis_number",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="engine",
            name="engine_number",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
